import{$ as a,fmt as w,posterGrad as L,dayName as T,ICONS as h}from"./helpers.js";import{isAdmin as H}from"./auth.js";import{state as r}from"./state.js";import{getPlaceById as I,getEventsForPlace as k}from"./places.js";import"./map-core.js";import"./toast.js";let b=null;export function initPlaceDetail({onOpenEventCard:o}){b=o}export function openPlaceDetail(o){const i=I(o);if(!i)return;const n=a("place-detail-poster");n&&(n.style.background=L(i.id),n.classList.remove("expanded"));const l=a("place-poster-inner"),D=a("place-poster-initial");if(l){l.innerHTML="";const t=i.imageUrl?.trim()||null;if(t){r.placeDetailHasImage=!0,n&&(n.style.cursor="zoom-in");const e=document.createElement("img");e.src=t,e.alt=i.name,e.loading="lazy";const s=()=>{r.placeDetailHasImage=!1,n&&(n.style.cursor="default"),l.innerHTML=x(i.name)};e.onerror=s,e.onabort=s,e.onload=()=>{r.placeDetailHasImage=!0,n&&(n.style.cursor="zoom-in"),l.innerHTML="",l.appendChild(e)},l.appendChild(e)}else r.placeDetailHasImage=!1,n&&(n.style.cursor="default"),l.innerHTML=x(i.name)}const m=a("place-detail-title"),f=a("place-detail-meta"),v=a("place-detail-desc");if(m&&(m.textContent=i.name),f){let t="";t+=`<div class="meta-row">${h.PIN}${i.address||"\u2014"}</div>`,i.time&&(t+=`<div class="meta-row">${h.CLK}${i.time}</div>`),f.innerHTML=t}v&&(v.textContent=i.description||"");const d=a("place-events-section"),c=a("place-events-list");if(d&&c){const t=k(i);t.length?(d.style.display="",c.innerHTML=t.map(e=>{const s=e.date===w(new Date)?"\u0421\u0435\u0433\u043E\u0434\u043D\u044F":T(e.date);return`
          <div class="place-event-item" data-event-id="${e.id}">
            <div class="place-event-dot"></div>
            <div class="place-event-info">
              <div class="place-event-name">${e.title}</div>
              <div class="place-event-date">${s} \xB7 ${e.time||""}</div>
            </div>
          </div>`}).join(""),c.querySelectorAll(".place-event-item").forEach(e=>{e.addEventListener("click",()=>{const s=e.getAttribute("data-event-id");closePlaceDetail(),b?.(s)})})):(d.style.display="",c.innerHTML='<p class="place-events-empty">\u041F\u043E\u043A\u0430 \u043D\u0435\u0442 \u043F\u0440\u0435\u0434\u0441\u0442\u043E\u044F\u0449\u0438\u0445 \u0441\u043E\u0431\u044B\u0442\u0438\u0439</p>')}const g=a("btn-place-detail-share");g&&(g.onclick=()=>{const t=window.location.origin+window.location.pathname+"?place="+o;navigator.share?navigator.share({title:i.name,url:t}).catch(()=>{}):navigator.clipboard&&navigator.clipboard.writeText(t)});const u=a("place-admin-actions");if(u&&u.remove(),H()){const t=a("place-detail-body");if(t){const e=document.createElement("div");e.id="place-admin-actions",e.style.cssText="display:flex;gap:8px;margin-top:14px;padding-top:12px;border-top:1px solid var(--c-soft-br)",e.innerHTML=`
        <button class="btn-admin-detail edit" id="place-admin-edit" style="flex:1;height:38px;border-radius:var(--r-b);background:var(--c-glass);border:1.5px solid var(--c-glass-br);color:var(--c-accent);font-size:12px;font-weight:700;display:flex;align-items:center;justify-content:center;gap:5px">
          <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/>
            <path d="m18.5 2.5 3 3L12 15l-4 1 1-4 9.5-9.5z"/>
          </svg>
          \u0420\u0435\u0434\u0430\u043A\u0442\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u043C\u0435\u0441\u0442\u043E
        </button>
      `,t.appendChild(e),e.querySelector("#place-admin-edit")?.addEventListener("click",async()=>{closePlaceDetail(),(await import("./admin.js")).openAdminPanel()})}}const p=a("place-detail");p&&(p.classList.add("open"),p.setAttribute("aria-hidden","false"));const y=a("place-detail-body");y&&(y.scrollTop=0)}export function closePlaceDetail(){const o=a("place-detail");o&&(o.classList.remove("open"),o.setAttribute("aria-hidden","true"))}function x(o){return`<img src="assets/Group 27.png" alt="${o||""}"
               style="width:40%;height:40%;object-fit:contain;margin:auto;display:block;">`}
